name: aha ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  acceptance_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: Verify Java version
        run: java -version

      - name: Set up Maven
        run: mvn -v

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
            path: ~/.m2
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn -B clean install -DskipTests

      - name: Run Tests and Generate Reports
        run: mvn verify
